default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: secretPlains_development

test:
  <<: *default
  database: secretPlains_test

production:
  <<: *default
  database: secretPlains_production
  username: secretPlains
  password: <%= ENV['SECRETPLAINS_DATABASE_PASSWORD'] %>
